name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'  # Changed from 'adoptopenjdk' to 'temurin'

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('src/adservice/**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Ensure Gradle Wrapper is Executable
      run: chmod +x src/adservice/gradlew

    - name: Print Gradle Wrapper Version
      run: src/adservice/gradlew --version

    - name: Verify Gradle Wrapper
      run: src/adservice/gradlew --version

    - name: Build and Analyze
      env:
        SONAR_HOST_URL: http://127.0.0.1:9000
        SONAR_AUTH_TOKEN: ${{ secrets.sonar }}
      run: src/adservice/gradlew build sonarqube \
        -Dsonar.projectKey=my-project \
        -Dsonar.pullrequest.key=${{ github.event.pull_request.number }} \
        -Dsonar.pullrequest.branch=${{ github.head_ref }} \
        -Dsonar.pullrequest.base=${{ github.base_ref }} \
        -Dsonar.host.url=${SONAR_HOST_URL} \
        -Dsonar.login=${SONAR_AUTH_TOKEN}
