name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin' # Use 'temurin' distribution, as 'adoptopenjdk' is deprecated

    - name: Set up Gradle
      uses: gradle/gradle-build-action@v3
      with:
        gradle-version: '8.7' # Ensure the version matches your project's requirements

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build and Analyze
      env:
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_AUTH_TOKEN: ${{ secrets.SONAR_AUTH_TOKEN }}
      run: ./gradlew build sonar \
        -Dsonar.projectKey=my-project \
        -Dsonar.pullrequest.key=${{ github.event.pull_request.number }} \
        -Dsonar.pullrequest.branch=${{ github.head_ref }} \
        -Dsonar.pullrequest.base=${{ github.base_ref }} \
        -Dsonar.host.url=${{ env.SONAR_HOST_URL }} \
        -Dsonar.login=${{ env.SONAR_AUTH_TOKEN }}
